document.addEventListener('DOMContentLoaded', () => {
    const stateSelect = document.getElementById('state');
    const departmentSelect = document.getElementById('department');

    // Departments mapped by state and category
    const departments = {
        home_electricity: {
            'AP': ['Andhra Pradesh Eastern Power Distribution Company Limited (APEPDCL)',
                'Andhra Pradesh Southern Power Distribution Company Limited (APSPDCL)'],
            'AR': ['Department of Power'],
            'AS': ['Assam Power Distribution Company Limited (APDCL)'],
            'BR': ['North Bihar Power Distribution Company Limited (NBPDCL)',
                'South Bihar Power Distribution Company Limited (SBPDCL)'],
            'CG': ['Chhattisgarh State Power Distribution Company Limited (CSPDCL)'],
            'GJ': ['Dakshin Gujarat Vij Company Limited (DGVCL)',
                'Madhya Gujarat Vij Company Limited (MGVCL)',
                'Paschim Gujarat Vij Company Limited (PGVCL)',
                'Uttar Gujarat Vij Company Limited (UGVCL)'
            ],
            'HR': ['Uttar Haryana Bijli Vitran Nigam Limited (UHBVN)',
                'Dakshin Haryana Bijli Vitran Nigam Limited (DHBVN)'
            ],
            'HP': ['Himachal Pradesh State Electricity Board Limited (HPSEB)'],
            'JK': ['Jammu Power Distribution Corporation Limited (JPDCL)',
                'Kashmir Power Distribution Corporation Limited (KPDCL)'
            ],
            'GA': ['Goa Electricity Department (GED)'],
            'JH': ['Jharkhand Bijli Vitran Nigam Limited (JBVNL)'],
            'KA': ['Bangalore Electricity Supply Company Limited (BESCOM)',
                'Mangalore Electricity Supply Company Limited (MESCOM)',
                'Hubli Electricity Supply Company Limited (HESCOM)',
                'Gulbarga Electricity Supply Company Limited (GESCOM)',
                'Chamundeshwari Electricity Supply Corporation Limited (CESC)'
            ],
            'KL': ['Kerala State Electricity Board (KSEB)'],
            'MP': ['Madhya Pradesh Paschim Kshetra Vidyut Vitran Company Limited (MPPKVVCL)',
                'Madhya Pradesh Madhya Kshetra Vidyut Vitran Company Limited (MPMKVVCL)',
                'Madhya Pradesh Poorv Kshetra Vidyut Vitran Company Limited (MPPoKVVCL)'
            ],
            'MH': ['Maharashtra State Electricity Distribution Company Limited (MSEDCL or Mahavitaran)',
                'Tata Power',
                'Adani Electricity Mumbai Limited (AEML)',
                'BEST Undertaking (in Mumbai)'
            ],
            'MN': ['Manipur State Power Distribution Company Limited (MSPDCL)'],
            'ML': ['Meghalaya Power Distribution Corporation Limited (MePDCL)'],
            'MZ': ['Power and Electricity Department, Government of Mizoram'],
            'NL': ['Department of Power, Nagaland'],
            'OD': ['Tata Power Central Odisha Distribution Limited (TPCODL)',
                'Tata Power Western Odisha Distribution Limited (TPWODL)',
                'Tata Power Southern Odisha Distribution Limited (TPSODL)',
                'Tata Power Northern Odisha Distribution Limited (TPNODL)'
            ],
            'PB': ['Punjab State Power Corporation Limited (PSPCL)'],
            'PY': ['Electricity Department, Government of Puducherry'],
            'RJ': ['Jaipur Vidyut Vitran Nigam Limited (JVVNL)',
                'Ajmer Vidyut Vitran Nigam Limited (AVVNL)',
                'Jodhpur Vidyut Vitran Nigam Limited (JdVVNL)'
            ],
            'SK': ['Power Department, Government of Sikkim'],
            'TN': ['Tamil Nadu Generation and Distribution Corporation Limited (TANGEDCO)'],
            'TS': ['Telangana State Southern Power Distribution Company Limited (TSSPDCL)',
                'Telangana State Northern Power Distribution Company Limited (TSNPDCL)'
            ],
            'TR': ['Tripura State Electricity Corporation Limited (TSECL)'],
            'UK': ['Uttarakhand Power Corporation Limited (UPCL)'],
            'UP': ['Purvanchal Vidyut Vitran Nigam Limited (PVVNL)',
                'Dakshinanchal Vidyut Vitran Nigam Limited (DVVNL)',
                'Madhyanchal Vidyut Vitran Nigam Limited (MVVNL)',
                'Paschimanchal Vidyut Vitran Nigam Limited (PuVVNL)'
            ],
            'WB': ['West Bengal State Electricity Distribution Company Limited (WBSEDCL)',
                'Calcutta Electric Supply Corporation (CESC, Kolkata)'
            ],
            'AN': ['Electricity Department, Andaman and Nicobar Islands'],
            'CH': ['Chandigarh Electricity Department'],
            'DN': ['DNHPDCL (Dadra and Nagar Haveli Power Distribution Corporation Limited)'],
            'DD': ['DNHPDCL (Dadra and Nagar Haveli Power Distribution Corporation Limited)'],
            'DL': ['BSES Rajdhani Power Limited (BRPL)',
                'BSES Yamuna Power Limited (BYPL)',
                'Tata Power Delhi Distribution Limited (TPDDL)'
            ],
            'LD': ['Lakshadweep Electricity Department'],
            'PY': ['Electricity Department, Government of Puducherry']
        },

        street_lights: {
            'AP': ["Visakhapatnam Municipal Corporation",
                "Vijayawada Municipal Corporation",
                "Guntur Municipal Corporation",
                "Kakinada Municipal Corporation",
                "Nellore Municipal Corporation",
                "Tirupati Municipal Corporation",
                "Anantapur Municipal Corporation",
                "Kadapa Municipal Corporation",
                "Kurnool Municipal Corporation",
                "Ongole Municipal Corporation",
                "Eluru Municipal Corporation"
            ],
            'AR': ["Itanagar Municipal Corporation"],
            'AS': ["Guwahati Municipal Corporation"],
            'BR': ["Patna Municipal Corporation",
                "Gaya Municipal Corporation",
                "Bhagalpur Municipal Corporation",
                "Muzaffarpur Municipal Corporation",
                "Darbhanga Municipal Corporation",
                "Bihar Sharif Municipal Corporation"
            ],
            'CG': ["Raipur Municipal Corporation",
                "Durg-Bhilai Municipal Corporation",
                "Bilaspur Municipal Corporation",
                "Korba Municipal Corporation",
                "Rajnandgaon Municipal Corporation"
            ],
            'GJ': ["Ahmedabad Municipal Corporation",
                "Surat Municipal Corporation",
                "Vadodara Municipal Corporation",
                "Rajkot Municipal Corporation",
                "Bhavnagar Municipal Corporation",
                "Jamnagar Municipal Corporation",
                "Gandhinagar Municipal Corporation",
                "Junagadh Municipal Corporation"  
            ],
            'HR': ["Faridabad Municipal Corporation",
                "Gurugram Municipal Corporation",
                "Ambala Municipal Corporation",
                "Karnal Municipal Corporation",
                "Panipat Municipal Corporation",
                "Hisar Municipal Corporation",
                "Rohtak Municipal Corporation",
                "Yamunanagar Municipal Corporation",
                "Sonipat Municipal Corporation",
                "Panchkula Municipal Corporation"
            ],
            'HP': ["Shimla Municipal Corporation"],
            'JK': ["Jammu Municipal Corporation",
                "Srinagar Municipal Corporation"
            ],
            'GA': ["Panaji Municipal Corporation (Corporation of the City of Panaji)"],
            'JH': ["Ranchi Municipal Corporation",
                "Dhanbad Municipal Corporation",
                "Jamshedpur Notified Area Committee",
                "Bokaro Municipal Corporation",
                "Hazaribagh Municipal Corporation"
            ],
            'KA': ["Bengaluru Municipal Corporation (BBMP)",
                "Mysuru Municipal Corporation",
                "Hubballi-Dharwad Municipal Corporation",
                "Mangaluru Municipal Corporation",
                "Belagavi Municipal Corporation",
                "Kalaburagi Municipal Corporation",
                "Ballari Municipal Corporation",
                "Shivamogga Municipal Corporation",
                "Davangere Municipal Corporation",
                "Tumakuru Municipal Corporation"
            ],
            'KL': ["Thiruvananthapuram Municipal Corporation",
                "Kochi Municipal Corporation",
                "Kozhikode Municipal Corporation",
                "Kollam Municipal Corporation",
                "Thrissur Municipal Corporation",
                "Kannur Municipal Corporation"
            ],
            'MP': ["Bhopal Municipal Corporation",
                "Indore Municipal Corporation",
                "Jabalpur Municipal Corporation",
                "Gwalior Municipal Corporation",
                "Ujjain Municipal Corporation",
                "Sagar Municipal Corporation",
                "Satna Municipal Corporation",
                "Rewa Municipal Corporation",
                "Katni Municipal Corporation"
            ],
            'MH': ["Mumbai Municipal Corporation (MCGM)",
                "Pune Municipal Corporation",
                "Nagpur Municipal Corporation",
                "Nashik Municipal Corporation",
                "Thane Municipal Corporation",
                "Navi Mumbai Municipal Corporation",
                "Aurangabad Municipal Corporation",
                "Solapur Municipal Corporation",
                "Amravati Municipal Corporation",
                "Kolhapur Municipal Corporation"
            ],
            'MN': ["Imphal Municipal Corporation"],
            'ML': ["Shillong Municipal Board"],
            'MZ': ["Aizawl Municipal Corporation"],
            'NL': ["Kohima Municipal Council",
                "Dimapur Municipal Council"
            ],
            'OD': ["Bhubaneswar Municipal Corporation",
                "Cuttack Municipal Corporation",
                "Berhampur Municipal Corporation",
                "Sambalpur Municipal Corporation",
                "Rourkela Municipal Corporation"
            ],
            'PB': ["Ludhiana Municipal Corporation",
                "Amritsar Municipal Corporation",
                "Jalandhar Municipal Corporation",
                "Patiala Municipal Corporation",
                "Bathinda Municipal Corporation",
                "Mohali Municipal Corporation"
            ],
            'RJ': ["Jaipur Municipal Corporation",
                "Jodhpur Municipal Corporation",
                "Kota Municipal Corporation",
                "Udaipur Municipal Corporation",
                "Ajmer Municipal Corporation",
                "Bikaner Municipal Corporation"
            ],
            'SK': ["Gangtok Municipal Corporation"],
            'TN': ["Chennai Municipal Corporation",
                "Coimbatore Municipal Corporation",
                "Madurai Municipal Corporation",
                "Tiruchirappalli Municipal Corporation",
                "Salem Municipal Corporation",
                "Tirunelveli Municipal Corporation",
                "Erode Municipal Corporation",
                "Vellore Municipal Corporation",
                "Thoothukudi Municipal Corporation",
                "Dindigul Municipal Corporation",
                "Hosur Municipal Corporation"
            ],
            'TS': ["Greater Hyderabad Municipal Corporation",
                "Warangal Municipal Corporation",
                "Nizamabad Municipal Corporation",
                "Karimnagar Municipal Corporation",
                "Khammam Municipal Corporation",
                "Ramagundam Municipal Corporation"
            ],
            'TR': ["Agartala Municipal Corporation"],
            'UP': ["Lucknow Municipal Corporation",
                "Kanpur Municipal Corporation",
                "Agra Municipal Corporation",
                "Varanasi Municipal Corporation",
                "Allahabad (Prayagraj) Municipal Corporation",
                "Ghaziabad Municipal Corporation",
                "Meerut Municipal Corporation",
                "Aligarh Municipal Corporation",
                "Moradabad Municipal Corporation",
                "Saharanpur Municipal Corporation",
                "Bareilly Municipal Corporation",
                "Gorakhpur Municipal Corporation"
            ],
            'UK': ["Dehradun Municipal Corporation",
                "Haridwar Municipal Corporation",
                "Haldwani Municipal Corporation",
                "Roorkee Municipal Corporation",
                "Kashipur Municipal Corporation"
            ],
            'WB': ["Kolkata Municipal Corporation",
                "Howrah Municipal Corporation",
                "Durgapur Municipal Corporation",
                "Asansol Municipal Corporation",
                "Siliguri Municipal Corporation",
                "Chandannagar Municipal Corporation"
            ],
            'AN': ["Port Blair Municipal Council"],
            'CH': ["Chandigarh Municipal Corporation"],
            'DN': ["Daman Municipal Council",
                "Diu Municipal Council",
                "Silvassa Municipal Council"
            ],
            'DD': ["Daman Municipal Council",
                "Diu Municipal Council",
                "Silvassa Municipal Council"
            ],
            'LD': ["Kavaratti Town Municipal Council"],
            'DL': ["North Delhi Municipal Corporation (NDMC)",
                "South Delhi Municipal Corporation (SDMC)",
                "East Delhi Municipal Corporation (EDMC)",
                "New Delhi Municipal Council (NDMC)"
            ],
            'PY': ["Puducherry Municipal Council",
                "Oulgaret Municipal Council",
                "Karaikal Municipal Council",
                "Mahe Municipal Council",
                "Yanam Municipal Council"
            ],
        },

        potholes: {
            'AP': ["Visakhapatnam Municipal Corporation",
                "Vijayawada Municipal Corporation",
                "Guntur Municipal Corporation",
                "Kakinada Municipal Corporation",
                "Nellore Municipal Corporation",
                "Tirupati Municipal Corporation",
                "Anantapur Municipal Corporation",
                "Kadapa Municipal Corporation",
                "Kurnool Municipal Corporation",
                "Ongole Municipal Corporation",
                "Eluru Municipal Corporation"
            ],
            'AR': ["Itanagar Municipal Corporation"],
            'AS': ["Guwahati Municipal Corporation"],
            'BR': ["Patna Municipal Corporation",
                "Gaya Municipal Corporation",
                "Bhagalpur Municipal Corporation",
                "Muzaffarpur Municipal Corporation",
                "Darbhanga Municipal Corporation",
                "Bihar Sharif Municipal Corporation"
            ],
            'CG': ["Raipur Municipal Corporation",
                "Durg-Bhilai Municipal Corporation",
                "Bilaspur Municipal Corporation",
                "Korba Municipal Corporation",
                "Rajnandgaon Municipal Corporation"
            ],
            'GJ': ["Ahmedabad Municipal Corporation",
                "Surat Municipal Corporation",
                "Vadodara Municipal Corporation",
                "Rajkot Municipal Corporation",
                "Bhavnagar Municipal Corporation",
                "Jamnagar Municipal Corporation",
                "Gandhinagar Municipal Corporation",
                "Junagadh Municipal Corporation"  
            ],
            'HR': ["Faridabad Municipal Corporation",
                "Gurugram Municipal Corporation",
                "Ambala Municipal Corporation",
                "Karnal Municipal Corporation",
                "Panipat Municipal Corporation",
                "Hisar Municipal Corporation",
                "Rohtak Municipal Corporation",
                "Yamunanagar Municipal Corporation",
                "Sonipat Municipal Corporation",
                "Panchkula Municipal Corporation"
            ],
            'HP': ["Shimla Municipal Corporation"],
            'JK': ["Jammu Municipal Corporation",
                "Srinagar Municipal Corporation"
            ],
            'GA': ["Panaji Municipal Corporation (Corporation of the City of Panaji)"],
            'JH': ["Ranchi Municipal Corporation",
                "Dhanbad Municipal Corporation",
                "Jamshedpur Notified Area Committee",
                "Bokaro Municipal Corporation",
                "Hazaribagh Municipal Corporation"
            ],
            'KA': ["Bengaluru Municipal Corporation (BBMP)",
                "Mysuru Municipal Corporation",
                "Hubballi-Dharwad Municipal Corporation",
                "Mangaluru Municipal Corporation",
                "Belagavi Municipal Corporation",
                "Kalaburagi Municipal Corporation",
                "Ballari Municipal Corporation",
                "Shivamogga Municipal Corporation",
                "Davangere Municipal Corporation",
                "Tumakuru Municipal Corporation"
            ],
            'KL': ["Thiruvananthapuram Municipal Corporation",
                "Kochi Municipal Corporation",
                "Kozhikode Municipal Corporation",
                "Kollam Municipal Corporation",
                "Thrissur Municipal Corporation",
                "Kannur Municipal Corporation"
            ],
            'MP': ["Bhopal Municipal Corporation",
                "Indore Municipal Corporation",
                "Jabalpur Municipal Corporation",
                "Gwalior Municipal Corporation",
                "Ujjain Municipal Corporation",
                "Sagar Municipal Corporation",
                "Satna Municipal Corporation",
                "Rewa Municipal Corporation",
                "Katni Municipal Corporation"
            ],
            'MH': ["Mumbai Municipal Corporation (MCGM)",
                "Pune Municipal Corporation",
                "Nagpur Municipal Corporation",
                "Nashik Municipal Corporation",
                "Thane Municipal Corporation",
                "Navi Mumbai Municipal Corporation",
                "Aurangabad Municipal Corporation",
                "Solapur Municipal Corporation",
                "Amravati Municipal Corporation",
                "Kolhapur Municipal Corporation"
            ],
            'MN': ["Imphal Municipal Corporation"],
            'ML': ["Shillong Municipal Board"],
            'MZ': ["Aizawl Municipal Corporation"],
            'NL': ["Kohima Municipal Council",
                "Dimapur Municipal Council"
            ],
            'OD': ["Bhubaneswar Municipal Corporation",
                "Cuttack Municipal Corporation",
                "Berhampur Municipal Corporation",
                "Sambalpur Municipal Corporation",
                "Rourkela Municipal Corporation"
            ],
            'PB': ["Ludhiana Municipal Corporation",
                "Amritsar Municipal Corporation",
                "Jalandhar Municipal Corporation",
                "Patiala Municipal Corporation",
                "Bathinda Municipal Corporation",
                "Mohali Municipal Corporation"
            ],
            'RJ': ["Jaipur Municipal Corporation",
                "Jodhpur Municipal Corporation",
                "Kota Municipal Corporation",
                "Udaipur Municipal Corporation",
                "Ajmer Municipal Corporation",
                "Bikaner Municipal Corporation"
            ],
            'SK': ["Gangtok Municipal Corporation"],
            'TN': ["Chennai Municipal Corporation",
                "Coimbatore Municipal Corporation",
                "Madurai Municipal Corporation",
                "Tiruchirappalli Municipal Corporation",
                "Salem Municipal Corporation",
                "Tirunelveli Municipal Corporation",
                "Erode Municipal Corporation",
                "Vellore Municipal Corporation",
                "Thoothukudi Municipal Corporation",
                "Dindigul Municipal Corporation",
                "Hosur Municipal Corporation"
            ],
            'TS': ["Greater Hyderabad Municipal Corporation",
                "Warangal Municipal Corporation",
                "Nizamabad Municipal Corporation",
                "Karimnagar Municipal Corporation",
                "Khammam Municipal Corporation",
                "Ramagundam Municipal Corporation"
            ],
            'TR': ["Agartala Municipal Corporation"],
            'UP': ["Lucknow Municipal Corporation",
                "Kanpur Municipal Corporation",
                "Agra Municipal Corporation",
                "Varanasi Municipal Corporation",
                "Allahabad (Prayagraj) Municipal Corporation",
                "Ghaziabad Municipal Corporation",
                "Meerut Municipal Corporation",
                "Aligarh Municipal Corporation",
                "Moradabad Municipal Corporation",
                "Saharanpur Municipal Corporation",
                "Bareilly Municipal Corporation",
                "Gorakhpur Municipal Corporation"
            ],
            'UK': ["Dehradun Municipal Corporation",
                "Haridwar Municipal Corporation",
                "Haldwani Municipal Corporation",
                "Roorkee Municipal Corporation",
                "Kashipur Municipal Corporation"
            ],
            'WB': ["Kolkata Municipal Corporation",
                "Howrah Municipal Corporation",
                "Durgapur Municipal Corporation",
                "Asansol Municipal Corporation",
                "Siliguri Municipal Corporation",
                "Chandannagar Municipal Corporation"
            ],
            'AN': ["Port Blair Municipal Council"],
            'CH': ["Chandigarh Municipal Corporation"],
            'DN': ["Daman Municipal Council",
                "Diu Municipal Council",
                "Silvassa Municipal Council"
            ],
            'DD': ["Daman Municipal Council",
                "Diu Municipal Council",
                "Silvassa Municipal Council"
            ],
            'LD': ["Kavaratti Town Municipal Council"],
            'DL': ["North Delhi Municipal Corporation (NDMC)",
                "South Delhi Municipal Corporation (SDMC)",
                "East Delhi Municipal Corporation (EDMC)",
                "New Delhi Municipal Council (NDMC)"
            ],
            'PY': ["Puducherry Municipal Council",
                "Oulgaret Municipal Council",
                "Karaikal Municipal Council",
                "Mahe Municipal Council",
                "Yanam Municipal Council"
            ],
        },

        garbage: {
            'AP': ["Visakhapatnam Municipal Corporation",
                "Vijayawada Municipal Corporation",
                "Guntur Municipal Corporation",
                "Kakinada Municipal Corporation",
                "Nellore Municipal Corporation",
                "Tirupati Municipal Corporation",
                "Anantapur Municipal Corporation",
                "Kadapa Municipal Corporation",
                "Kurnool Municipal Corporation",
                "Ongole Municipal Corporation",
                "Eluru Municipal Corporation"
            ],
            'AR': ["Itanagar Municipal Corporation"],
            'AS': ["Guwahati Municipal Corporation"],
            'BR': ["Patna Municipal Corporation",
                "Gaya Municipal Corporation",
                "Bhagalpur Municipal Corporation",
                "Muzaffarpur Municipal Corporation",
                "Darbhanga Municipal Corporation",
                "Bihar Sharif Municipal Corporation"
            ],
            'CG': ["Raipur Municipal Corporation",
                "Durg-Bhilai Municipal Corporation",
                "Bilaspur Municipal Corporation",
                "Korba Municipal Corporation",
                "Rajnandgaon Municipal Corporation"
            ],
            'GJ': ["Ahmedabad Municipal Corporation",
                "Surat Municipal Corporation",
                "Vadodara Municipal Corporation",
                "Rajkot Municipal Corporation",
                "Bhavnagar Municipal Corporation",
                "Jamnagar Municipal Corporation",
                "Gandhinagar Municipal Corporation",
                "Junagadh Municipal Corporation"  
            ],
            'HR': ["Faridabad Municipal Corporation",
                "Gurugram Municipal Corporation",
                "Ambala Municipal Corporation",
                "Karnal Municipal Corporation",
                "Panipat Municipal Corporation",
                "Hisar Municipal Corporation",
                "Rohtak Municipal Corporation",
                "Yamunanagar Municipal Corporation",
                "Sonipat Municipal Corporation",
                "Panchkula Municipal Corporation"
            ],
            'HP': ["Shimla Municipal Corporation"],
            'JK': ["Jammu Municipal Corporation",
                "Srinagar Municipal Corporation"
            ],
            'GA': ["Panaji Municipal Corporation (Corporation of the City of Panaji)"],
            'JH': ["Ranchi Municipal Corporation",
                "Dhanbad Municipal Corporation",
                "Jamshedpur Notified Area Committee",
                "Bokaro Municipal Corporation",
                "Hazaribagh Municipal Corporation"
            ],
            'KA': ["Bengaluru Municipal Corporation (BBMP)",
                "Mysuru Municipal Corporation",
                "Hubballi-Dharwad Municipal Corporation",
                "Mangaluru Municipal Corporation",
                "Belagavi Municipal Corporation",
                "Kalaburagi Municipal Corporation",
                "Ballari Municipal Corporation",
                "Shivamogga Municipal Corporation",
                "Davangere Municipal Corporation",
                "Tumakuru Municipal Corporation"
            ],
            'KL': ["Thiruvananthapuram Municipal Corporation",
                "Kochi Municipal Corporation",
                "Kozhikode Municipal Corporation",
                "Kollam Municipal Corporation",
                "Thrissur Municipal Corporation",
                "Kannur Municipal Corporation"
            ],
            'MP': ["Bhopal Municipal Corporation",
                "Indore Municipal Corporation",
                "Jabalpur Municipal Corporation",
                "Gwalior Municipal Corporation",
                "Ujjain Municipal Corporation",
                "Sagar Municipal Corporation",
                "Satna Municipal Corporation",
                "Rewa Municipal Corporation",
                "Katni Municipal Corporation"
            ],
            'MH': ["Mumbai Municipal Corporation (MCGM)",
                "Pune Municipal Corporation",
                "Nagpur Municipal Corporation",
                "Nashik Municipal Corporation",
                "Thane Municipal Corporation",
                "Navi Mumbai Municipal Corporation",
                "Aurangabad Municipal Corporation",
                "Solapur Municipal Corporation",
                "Amravati Municipal Corporation",
                "Kolhapur Municipal Corporation"
            ],
            'MN': ["Imphal Municipal Corporation"],
            'ML': ["Shillong Municipal Board"],
            'MZ': ["Aizawl Municipal Corporation"],
            'NL': ["Kohima Municipal Council",
                "Dimapur Municipal Council"
            ],
            'OD': ["Bhubaneswar Municipal Corporation",
                "Cuttack Municipal Corporation",
                "Berhampur Municipal Corporation",
                "Sambalpur Municipal Corporation",
                "Rourkela Municipal Corporation"
            ],
            'PB': ["Ludhiana Municipal Corporation",
                "Amritsar Municipal Corporation",
                "Jalandhar Municipal Corporation",
                "Patiala Municipal Corporation",
                "Bathinda Municipal Corporation",
                "Mohali Municipal Corporation"
            ],
            'RJ': ["Jaipur Municipal Corporation",
                "Jodhpur Municipal Corporation",
                "Kota Municipal Corporation",
                "Udaipur Municipal Corporation",
                "Ajmer Municipal Corporation",
                "Bikaner Municipal Corporation"
            ],
            'SK': ["Gangtok Municipal Corporation"],
            'TN': ["Chennai Municipal Corporation",
                "Coimbatore Municipal Corporation",
                "Madurai Municipal Corporation",
                "Tiruchirappalli Municipal Corporation",
                "Salem Municipal Corporation",
                "Tirunelveli Municipal Corporation",
                "Erode Municipal Corporation",
                "Vellore Municipal Corporation",
                "Thoothukudi Municipal Corporation",
                "Dindigul Municipal Corporation",
                "Hosur Municipal Corporation"
            ],
            'TS': ["Greater Hyderabad Municipal Corporation",
                "Warangal Municipal Corporation",
                "Nizamabad Municipal Corporation",
                "Karimnagar Municipal Corporation",
                "Khammam Municipal Corporation",
                "Ramagundam Municipal Corporation"
            ],
            'TR': ["Agartala Municipal Corporation"],
            'UP': ["Lucknow Municipal Corporation",
                "Kanpur Municipal Corporation",
                "Agra Municipal Corporation",
                "Varanasi Municipal Corporation",
                "Allahabad (Prayagraj) Municipal Corporation",
                "Ghaziabad Municipal Corporation",
                "Meerut Municipal Corporation",
                "Aligarh Municipal Corporation",
                "Moradabad Municipal Corporation",
                "Saharanpur Municipal Corporation",
                "Bareilly Municipal Corporation",
                "Gorakhpur Municipal Corporation"
            ],
            'UK': ["Dehradun Municipal Corporation",
                "Haridwar Municipal Corporation",
                "Haldwani Municipal Corporation",
                "Roorkee Municipal Corporation",
                "Kashipur Municipal Corporation"
            ],
            'WB': ["Kolkata Municipal Corporation",
                "Howrah Municipal Corporation",
                "Durgapur Municipal Corporation",
                "Asansol Municipal Corporation",
                "Siliguri Municipal Corporation",
                "Chandannagar Municipal Corporation"
            ],
            'AN': ["Port Blair Municipal Council"],
            'CH': ["Chandigarh Municipal Corporation"],
            'DN': ["Daman Municipal Council",
                "Diu Municipal Council",
                "Silvassa Municipal Council"
            ],
            'DD': ["Daman Municipal Council",
                "Diu Municipal Council",
                "Silvassa Municipal Council"
            ],
            'LD': ["Kavaratti Town Municipal Council"],
            'DL': ["North Delhi Municipal Corporation (NDMC)",
                "South Delhi Municipal Corporation (SDMC)",
                "East Delhi Municipal Corporation (EDMC)",
                "New Delhi Municipal Council (NDMC)"
            ],
            'PY': ["Puducherry Municipal Council",
                "Oulgaret Municipal Council",
                "Karaikal Municipal Council",
                "Mahe Municipal Council",
                "Yanam Municipal Council"
            ],
        }
    };

    // Get category from URL
    const urlParams = new URLSearchParams(window.location.search);
    const category = urlParams.get('category');

    // Load departments based on selected state and category
    stateSelect.addEventListener('change', () => {
        const selectedState = stateSelect.value;
        departmentSelect.innerHTML = '<option value="">Select Department</option>'; // Reset dropdown

        if (departments[category] && departments[category][selectedState]) {
            departments[category][selectedState].forEach(department => {
                const option = document.createElement('option');
                option.value = department;
                option.textContent = department;
                departmentSelect.appendChild(option);
            });
        }
    });
});


